{{- if .Values.global.alb.oidc.enabled }}
apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.appName }}-{{ .Values.global.environment }}-alb-oidc
data:
    clientId: {{ .Values.global.alb.oidc.clientId | b64enc | quote }}
    clientSecret: {{ .Values.global.alb.oidc.clientSecret |b64enc | quote }}
{{- end }}